# Generated by Django 5.0.1 on 2024-05-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Schools',
        ),
    ]
