# Generated by Django 5.0.1 on 2024-05-10 09:51

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(upload_to=news.models.generate_filename),
        ),
    ]
