# Generated by Django 5.0.1 on 2024-05-06 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
