# Generated by Django 5.0.1 on 2024-05-06 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
