# Generated by Django 5.0.1 on 2024-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(),
        ),
    ]
