# Generated by Django 5.0.1 on 2024-05-06 06:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_notice_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
